# Generated by Django 5.2.11 on 2026-05-29 09:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('dob', models.DateField(help_text='Date of Birth (YYYY-MM-DD)')),
                ('mobile', models.CharField(max_length=15)),
                ('pan_last4', models.CharField(help_text='Last 4 digits of PAN card', max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('id_document', models.ImageField(blank=True, help_text='Upload a valid ID document (Aadhaar/PAN)', null=True, upload_to='documents/%Y/%m/%d/')),
                ('selfie', models.ImageField(blank=True, help_text='Live selfie captured via webcam', null=True, upload_to='selfies/%Y/%m/%d/')),
                ('face_match_score', models.FloatField(blank=True, help_text='Face match score (0-1)', null=True)),
                ('face_match_passed', models.BooleanField(default=False, help_text='Did the face match pass the threshold?')),
                ('face_match_message', models.CharField(blank=True, help_text='Message from face match process', max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
