# Generated by Django 5.2.11 on 2026-06-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycapplication',
            name='face_match_message',
        ),
    ]
