# Generated by Django 5.2.11 on 2026-06-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_remove_kycapplication_face_match_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycapplication',
            name='face_match_message',
            field=models.CharField(blank=True, help_text='Message from face match process', max_length=255, null=True),
        ),
    ]
