# Generated by Django 5.2.11 on 2026-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_alter_kycapplication_status_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycapplication',
            name='face_match_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
