# Generated by Django 5.2.11 on 2026-06-03 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_kycapplication_face_match_skipped'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kycapplication',
            constraint=models.UniqueConstraint(fields=('mobile',), name='unique_mobile_in_kyc'),
        ),
        migrations.AddConstraint(
            model_name='kycapplication',
            constraint=models.UniqueConstraint(fields=('pan_last4',), name='unique_pan_in_kyc'),
        ),
    ]
