# Generated by Django 5.2.11 on 2026-06-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_kycapplication_unique_mobile_in_kyc_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kycapplication',
            name='unique_pan_in_kyc',
        ),
    ]
