# Generated by Django 5.2.11 on 2026-06-05 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_remove_kycapplication_unique_pan_in_kyc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kycapplication',
            name='unique_mobile_in_kyc',
        ),
        migrations.AddConstraint(
            model_name='kycapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('mobile',), name='unique_active_mobile'),
        ),
    ]
